### ISSUE TITLE
HIST table record status

### ISSUE THREAD

**Issue by hieu2102** [BNHTech/kafka-jdbc-sink-connector#5]
hist table have `RECORD_STATUS` column that should be processed separatedly

1. add connector's config
`RECORD_STATUS` != `VALUE`

2. add prepared statement
if RECORD_STATUS` != `VALUE` then
bind 
```sql
UPDATE table SET RECORD_STATUS = ${message.RECORD_STATUS}
...
```
else message is not a HIST table record -> process normally

**Comment by hieu2102** [comment]
error log for hist.table disabled
```
Caused by: org.apache.kafka.connect.errors.ConnectException: PK mode for table 'ODS_SEAB_CREDIT_INFO' is RECORD_VALUE with configured PK fields [null], but record value schema does not contain field: null
	at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extractRecordValuePk(FieldsMetadata.java:280)
	at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:105)
	at io.confluent.connect.jdbc.sink.metadata.FieldsMetadata.extract(FieldsMetadata.java:67)
	at vn.bnh.connect.jdbc.BufferedRecords.initHistRecordSchema(BufferedRecords.java:109)
	at vn.bnh.connect.jdbc.BufferedRecords.add(BufferedRecords.java:227)
	at vn.bnh.connect.jdbc.sink.JdbcAuditDbWriter.write(JdbcAuditDbWriter.java:75)
	at vn.bnh.connect.jdbc.sink.JdbcAuditSinkTask.put(JdbcAuditSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:593)
	... 11 more
```

**Comment by hieu2102** [comment]
error log for hist.table enabled
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.sql.PreparedStatement.executeBatch()" because "this.histTablePreparedStatement" is null
	at vn.bnh.connect.jdbc.BufferedRecords.executeHistUpdateStmt(BufferedRecords.java:287)
	at vn.bnh.connect.jdbc.BufferedRecords.flushWithDelete(BufferedRecords.java:176)
	at vn.bnh.connect.jdbc.BufferedRecords.flush(BufferedRecords.java:207)
	at vn.bnh.connect.jdbc.sink.JdbcAuditDbWriter.write(JdbcAuditDbWriter.java:81)
	at vn.bnh.connect.jdbc.sink.JdbcAuditSinkTask.put(JdbcAuditSinkTask.java:74)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:593)
	... 11 more
```
